module.exports = {
    content: [
      './**/*.html', // Add all HTML files
      './**/*.js',   // Include JavaScript files where classes might be added dynamically
    ],
    safelist: [
      'w-full',
      'min-h-screen',
      'flex',
      'flex-col',
      'items-center',
      'justify-start',
      'gap-[55px]',
      'pt-[40px]',
      'pb-[20px]',
      'bg-cover',
      'bg-center',
      'max-[480px]:p-[10px]',
      'w-[88%]',
      'max-[1024px]:w-full',
      'items-start',
      'max-[1024px]:items-center',
      'max-[1024px]:justify-center',
      'text-[100px]',
      'tracking-[3.5px]',
      'text-white',
      'font-normal',
      'max-[480px]:ml-[5px]',
      'max-[480px]:tracking-[1px]',
      'flex-wrap',
      'gap-[40px]',
      'mt-0',
      'w-[20%]',
      'max-[1024px]:w-[calc(33.333%-10px)]',
      'max-[1024px]:m-[15px]',
      'max-[768px]:w-[calc(50%-10px)]',
      'max-[768px]:m-[15px]',
      'h-[350px]',
      'rounded-[5px]',
      'relative',
      'shadow-[0px_0px_25px_rgba(255,255,255,0.5)]',
      'bg-white',
      'lg:m-[15px]',
      'max-[480px]:w-[calc(100%-10px)]',
      'max-[480px]:m-0',
      'max-[480px]:mt-[20px]',
      'w-[100px]',
      'h-[100px]',
      'object-cover',
      'rounded-full',
      'absolute',
      '-top-[50px]',
      'left-1/2',
      'transform',
      '-translate-x-1/2',
      'border-[5px]',
      'border-[#2A1768]',
      'justify-center',
      'gap-[10px]',
      'p-[20px]',
      'font-bold',
      'text-center',
      'text-[25px]',
      'font-semibold',
      'gap-[5px]',
      'font-medium',
      'text-[42px]',
      'text-[#2A1768]',
      'tracking-[1.3px]',
      'mt-[8px]',
      'gap-[28px]'
    ],
    theme: {
      extend: {
        // Add custom theme configurations if necessary
      }
    },
    plugins: [],
  }
  